
name: Trigger e2e cypress - Jenkins Job

on:
  push:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST https://morally-unlisping-janene.ngrok-free.dev/orange-hrm-e2e/build \
            --user amal_butmah:${{ secrets.JENKINS_API_TOKEN}}